# grpc_listener:
#   address: 0.0.0.0
#   port: 50051

# grpc_listener:
#   socket_path: /var/run/protocache/protocache.sock

http_server:
  address: 0.0.0.0
  port: 9091

tls:
  enabled: true
  cert_file: /etc/protocache/cert.pem
  key_file: /etc/protocache/key.pem

server:
  shutdown_timeout: 30s
  graceful_timeout: 10s

store:
  engine: "map"
  dump_enabled: true
  memory_dump_path: /var/lib/protocache/
  memory_dump_file_name: protocache.gob.gz